apiVersion: v1
kind: Namespace
metadata:
  name: cloud-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
  namespace: cloud-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: cloud-app-container
          image: 192.168.100.16:5000/my-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  namespace: cloud-namespace
spec:
  type: ClusterIP
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
